---
- name: Install docker python lib
  hosts: localhost
  tasks:
    - name : install lib docker
      pip:
        name: docker
        state: present

- name : Pull docker images
  hosts: server
  tasks:
    - name: Copy docker folder
      copy:
        src: ./docker
        dest: ~/
    - name: Build custom frr image
      docker_image:
        source: build
        name: "custom-frrouting/frr:v8.3.0"
        build:
          path: ~/docker/frrouting
          rm: yes
        state: present
    - name: Build custom ubuntu image
      docker_image:
        source: build
        name: "custom-ubuntu:focal"
        build:
          path: ~/docker/ubuntu
          rm: yes
        state: present
